### ISSUE TITLE
Readmeの更新

### ISSUE THREAD

**Issue by MizuokaDev** [MWindows99/TGR-Chino-Bot#5]
Readmeのコマンドプレフィックスが古いのになってるので要修正。

**Comment by MWindows99** [comment]
更新完了

**Comment by MizuokaDev** [comment]
こういう時は、コミットメッセージにissueの番号を書いて上げるとissueに結びついてくれるから良きよ。

例えばこんな感じ。
みずしゃんやらかしの対応 #2

ちなみに、closeとかfixとかいうやつをissueの前につけると自動でissueがクローズする。

例えばこんな感じ
fix #2 修正したお(´・ω・｀)

**Comment by MWindows99** [comment]
ほうほう
